<H1>Manual Controll of Feed export functionality</H1>
<ul style="display: block;
    font-size:16px;
    list-style-type: square;
    margin-top: 1em;
    margin-bottom: 1 em;
    margin-left: 0;
    margin-right: 0;
    padding-left: 40px;">
<li><h3>Export</h3></li>
<li><a href="<?php echo $this->getCreateUrl('feed-admin/manual/exportEdgeGoogle'); ?>">Export Edge Google</a></li>
<br />
<li><a href="<?php echo $this->getCreateUrl('feed-admin/manual/testEdgeGoogle'); ?>">TEST Edge Google</a></li>
<br />
<li><a href="<?php echo $this->getCreateUrl('feed-admin/manual/exportAll'); ?>">Export All</a></li>
